version: '3'

services:
  rails: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: "bundle exec pumactl start"
    env_file:
      - "./.env.dev"
    volumes:
      - ".:/workout_app"
      - "bundle:/usr/local/bundle"
      - "public:/workout_app/public"
      - "tmp:/workout_app/tmp"
      - "log:/workout_app/log"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    tty: true
    stdin_open: true
  webpack:
    <<: *app_base
    command: "bin/webpack-dev-server"
    ports:
      - "3035:3035"
    depends_on:
      - rails
    tty: false
    stdin_open: false
  db:
    image: "postgres:12-alpine"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  web:
    build:
      context: "containers/nginx"
    volumes:
      - "public:/workout_app/public"
      - "tmp:/workout_app/tmp"
    ports:
      - "80:80"
    depends_on:
      - rails
  chrome:
    image: "selenium/standalone-chrome"
    ports:
      - "4444:4444"
  terraform:
    image: "hashicorp/terraform:0.12.18"
    working_dir: "/terraform_eks"
    command: "tail -f /dev/null"
    volumes:
      - "./terraform_eks:/terraform_eks"
    entrypoint: []
    env_file:
      - "./.env.dev"

volumes:
  bundle:
  public:
  tmp:
  log:
  db: