apiVersion: v1
data:
  RAILS_MASTER_KEY: amTjJbiGUrNeWQcNWJGNrseBgwEWGp9ib9QFzt6KX3uUIp7/zkVAGzpxLaoYwzxD.36HtLwMnzZOxoZF/.t0WXEGQYgduzDHasMGNdwg==
kind: Secret
metadata:
  name: db-secret
type: Opaque
# kubesec:v:3
# kubesec:aws:arn:aws:kms:ap-northeast-1:012055136996:key/1814963e-29b5-46cf-aab0-655dfd2eb7e6:AQICAHiJovg0iK2aJ4dqv/sK1baLy4P1dPgRtcgByigcfW+PxgGzjyfehCOU8aqOxRH4/1MCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMId9YGyt5VA4wqj0RAgEQgDvaTsmVkayr/jX6C5Mu/14cfxCUdd/kS/uuicvRhtuZMKCk3wlVn1zQs/vrjtxJXGU06Ce3SrJPxFmdCw==
# kubesec:mac:0Ups6ejNwD2xBMj+.l+vhfC1I3bcMzIsqUbT9fg==
